# 系统配置
system:
  data_dir: "Multimodal_data"
  temp_dir: "temp"
  log_level: "INFO"

# 文档处理配置
document_processor:
  supported_formats:
    - "pdf"
    - "docx"
    - "xlsx"
    - "pptx"
  ocr:
    language: "chi_sim+eng"
    dpi: 300

# 图像处理配置
image_processor:
  model: "blip2"  # 可选: blip2, clip
  device: "cuda"  # 可选: cuda, cpu
  batch_size: 4
  image_size: 224

# 表格处理配置
table_processor:
  model: "tapas"
  max_rows: 100
  max_columns: 20

# 向量存储配置
vector_store:
  type: "faiss"
  dimension: 768
  index_type: "L2"
  nlist: 100
  nprobe: 10

# 检索配置
retrieval:
  top_k: 5
  similarity_threshold: 0.7
  reranker: "bge-reranker-base"

# LLM配置
llm:
  default_model: "chatglm3"  # 可选: chatglm3, qwen, gpt4
  temperature: 0.7
  max_tokens: 2048
  api_keys:
    openai: ""  # OpenAI API Key
    zhipu: ""   # 智谱API Key
    qwen: ""    # 通义千问API Key

# Web服务配置
web:
  host: "0.0.0.0"
  port: 8000
  debug: false
  static_dir: "static"
  template_dir: "templates" 